import { db, doctorsTable, testimonialsTable } from "@workspace/db";
import { eq } from "drizzle-orm";

export async function seedData() {
  // Seed doctors if none exist
  const existingDoctors = await db.select().from(doctorsTable).limit(1);
  if (existingDoctors.length === 0) {
    const doctors = [
      {
        clinicId: 1,
        name: "Dr. Ahmet Yilmaz",
        title: "MD, FACS",
        specialty: "Hair Transplant",
        licenseNumber: "TR-HT-2015-7842",
        yearsExperience: 12,
        certifications: ["ISHRS", "ABHRS", "ISHRS Fellow"],
        bio: "Pioneer in FUE and DHI techniques with over 12,000 successful procedures. Trained at Johns Hopkins Hospital.",
        languages: ["English", "Turkish", "German"],
        verified: true,
      },
      {
        clinicId: 1,
        name: "Dr. Selin Kaya",
        title: "MD, PhD",
        specialty: "Dental Surgery",
        licenseNumber: "TR-DS-2010-3421",
        yearsExperience: 15,
        certifications: ["ICOI", "ADA", "European Prosthodontic"],
        bio: "Specialist in full-mouth rehabilitation and implantology. Former consultant at King\'s College London.",
        languages: ["English", "Turkish", "French"],
        verified: true,
      },
      {
        clinicId: 2,
        name: "Dr. Mehmet Ozkan",
        title: "MD, FEBOPRAS",
        specialty: "Cosmetic Surgery",
        licenseNumber: "TR-CS-2008-9912",
        yearsExperience: 18,
        certifications: ["EBOPRAS", "ISAPS", "Turkish Society of Plastic Surgery"],
        bio: "Board-certified plastic surgeon with 18 years of experience. Specialises in rhinoplasty, VASER liposuction, and breast augmentation.",
        languages: ["English", "Turkish", "Arabic"],
        verified: true,
      },
      {
        clinicId: 2,
        name: "Dr. Fatma Demir",
        title: "MD",
        specialty: "Bariatric Surgery",
        licenseNumber: "TR-BS-2012-5623",
        yearsExperience: 13,
        certifications: ["IFSO", "ASMBS", "MIS Academy"],
        bio: "Leading bariatric surgeon with 3,000+ gastric sleeve and bypass procedures. Keynote speaker at IFSO 2023.",
        languages: ["English", "Turkish"],
        verified: true,
      },
      {
        clinicId: 3,
        name: "Dr. James Chen",
        title: "MD, PhD",
        specialty: "Cardiology",
        licenseNumber: "CN-CD-2011-4421",
        yearsExperience: 14,
        certifications: ["ESC", "ACC", "FSCAI"],
        bio: "Interventional cardiologist specialising in structural heart procedures and transcatheter interventions.",
        languages: ["English", "Mandarin", "Cantonese"],
        verified: true,
      },
      {
        clinicId: 4,
        name: "Dr. Wei Liu",
        title: "MD, MS",
        specialty: "Ophthalmology",
        licenseNumber: "CN-OP-2014-8834",
        yearsExperience: 11,
        certifications: ["AAO", "ESCRS", "ICO"],
        bio: "Refractive surgery specialist with 10,000+ LASIK and SMILE procedures. Former Moorfields Eye Hospital fellow.",
        languages: ["English", "Mandarin", "Japanese"],
        verified: true,
      },
      {
        clinicId: 5,
        name: "Dr. Li Wei",
        title: "MD, PhD",
        specialty: "Orthopedics",
        licenseNumber: "CN-OR-2009-1129",
        yearsExperience: 16,
        certifications: ["SICOT", "AAOS", "EFORT"],
        bio: "Joint replacement and sports medicine specialist. Pioneer in robotic-assisted knee replacement in China.",
        languages: ["English", "Mandarin", "Korean"],
        verified: true,
      },
    ];
    await db.insert(doctorsTable).values(doctors);
    console.log(`[seed] Inserted ${doctors.length} doctors`);
  }

  // Seed testimonials with blockchain fields if none exist
  const existingTestimonials = await db.select().from(testimonialsTable).limit(1);
  if (existingTestimonials.length === 0) {
    const testimonials = [
      {
        name: "Sarah M.",
        location: "London",
        procedure: "Hair Transplant",
        clinic: "EstePerla Hair Clinic",
        rating: "4.9",
        beforeText: "I was losing confidence due to hair loss. I had no idea how to even find a safe clinic abroad.",
        afterText: "VitaVia connected me to Dr. Yilmaz at EstePerla. 3,200 grafts, healed in 10 days. I saved £8,000 compared to the UK.",
        savings: "8000",
        avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=SarahM",
        anonymous: false,
        patientWallet: "0x742d35Cc6634C0532925a3b844Bc9e7595f8dEe",
        documentHash: "0x9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
        onChainTxHash: "0x3a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5",
        onChainTimestamp: new Date("2024-02-15T10:30:00Z"),
      },
      {
        name: "Anonymous",
        location: "Manchester",
        procedure: "Dental Implants",
        clinic: "Istanbul Smile Design",
        rating: "5.0",
        beforeText: "I was too embarrassed to smile at my wedding. UK dentists quoted me £22,000 for a full upper set.",
        afterText: "VitaVia found Istanbul Smile Design. £7,200 all-in. I smiled at my wedding and haven\'t stopped since.",
        savings: "15000",
        avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=anon1",
        anonymous: true,
        patientWallet: "0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B",
        documentHash: "0x7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8",
        onChainTxHash: "0x5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6",
        onChainTimestamp: new Date("2024-03-10T14:20:00Z"),
      },
      {
        name: "James R.",
        location: "Birmingham",
        procedure: "Gastric Sleeve",
        clinic: "Anatolia Medical Center",
        rating: "4.8",
        beforeText: "I was on the NHS waiting list for 18 months. My BMI was 42 and I felt desperate.",
        afterText: "Dr. Demir at Anatolia performed my sleeve. I lost 28kg in 4 months. The aftercare was world-class.",
        savings: "12000",
        avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=JamesR",
        anonymous: false,
        patientWallet: "0x8ba1f109551bD432803012645Hac136c89",
        documentHash: "0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2",
        onChainTxHash: "0x9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0",
        onChainTimestamp: new Date("2024-01-22T09:15:00Z"),
      },
      {
        name: "Anonymous",
        location: "Glasgow",
        procedure: "Rhinoplasty",
        clinic: "Istanbul Smile Design",
        rating: "4.7",
        beforeText: "I had a deviated septum and couldn\'t breathe properly. I was quoted £14,000 in London.",
        afterText: "Dr. Ozkan performed my rhinoplasty and septoplasty in one. I can breathe and my confidence is through the roof.",
        savings: "9800",
        avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=anon2",
        anonymous: true,
        patientWallet: "0xD4b4e3c2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4",
        documentHash: "0x2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3",
        onChainTxHash: "0x7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8",
        onChainTimestamp: new Date("2024-04-05T11:45:00Z"),
      },
      {
        name: "Emily T.",
        location: "Leeds",
        procedure: "LASIK Eye Surgery",
        clinic: "Shanghai Vision Center",
        rating: "5.0",
        beforeText: "I was -6.5 in both eyes and couldn\'t function without glasses. I was terrified of surgery abroad.",
        afterText: "Dr. Wei performed SMILE. 20/20 vision the next day. The whole trip was managed by VitaVia flawlessly.",
        savings: "4000",
        avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=EmilyT",
        anonymous: false,
        patientWallet: "0xE5c4d3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4",
        documentHash: "0x3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4",
        onChainTxHash: "0x8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9",
        onChainTimestamp: new Date("2024-05-18T08:30:00Z"),
      },
    ];
    await db.insert(testimonialsTable).values(testimonials);
    console.log(`[seed] Inserted ${testimonials.length} testimonials`);
  }
}
